/* DO NOT EDIT THIS FILE - it is machine generated */

#include "Android_log.h"
#include <jni.h>
/* Header for class work_wanghao_jni4ffmpeg_LibavHelper */

#ifndef _Included_work_wanghao_jni4ffmpeg_LibavHelper
#define _Included_work_wanghao_jni4ffmpeg_LibavHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     work_wanghao_jni4ffmpeg_LibavHelper
 * Method:    exec
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_work_wanghao_jni4ffmpeg_LibavHelper_exec
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
