/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class work_wanghao_jni4ffmpeg_Native4FFmpegHelper */

#ifndef _Included_work_wanghao_jni4ffmpeg_Native4FFmpegHelper
#define _Included_work_wanghao_jni4ffmpeg_Native4FFmpegHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     work_wanghao_jni4ffmpeg_Native4FFmpegHelper
 * Method:    run
 * Signature: (I[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_work_wanghao_jni4ffmpeg_Native4FFmpegHelper_run
  (JNIEnv *, jobject, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
